name: knee_oa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.15
  - pytorch=2.7.1
  - torchvision=0.22.1
  - cudatoolkit=11.8
  - numpy=2.4.3
  - scikit-learn=1.8.0
  - matplotlib=3.10.8
  - pandas=3.0.2
  - pillow=12.1.1
  - scipy=1.17.1
  - seaborn=0.13.2
  - tqdm=4.67.3
  - pyyaml=6.0.3
  - pip:
    - opencv-python==4.13.0.92
    - grad-cam==1.5.5
    - kaggle==2.0.1
    - quarto
