#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# setup.sh
# Creates the project folder structure for knee-oa-kl-grading.
#
# Usage:
#   bash setup.sh
#
# What it does:
#   - Creates all required directories
#   - Creates placeholder src/ Python files (empty, ready to fill)
#   - Does NOT download data or train models
#   - Safe to run multiple times (will not overwrite existing files)
# ─────────────────────────────────────────────────────────

set -e  # exit immediately if any command fails

echo ""
echo "============================================================"
echo "  knee-oa-kl-grading — Project Setup"
echo "============================================================"
echo ""

# ── 1. Create directory structure ────────────────────────
echo "[ 1 / 3 ]  Creating directories..."

dirs=(
    "data"
    "src"
    "notebooks"
    "results/checkpoints"
    "results/metrics"
    "results/gradcam/shared_misclassified"
    "results/gradcam/examples"
    "logs"
)

for d in "${dirs[@]}"; do
    if [ ! -d "$d" ]; then
        mkdir -p "$d"
        echo "  created  → $d"
    else
        echo "  exists   → $d"
    fi
done

echo ""

# ── 2. Create empty src/ placeholder files ───────────────
echo "[ 2 / 3 ]  Creating src/ placeholder files..."

src_files=(
    "src/losses.py"
    "src/dataset.py"
    "src/models.py"
    "src/train.py"
    "src/evaluate.py"
    "src/gradcam_audit.py"
)

for f in "${src_files[@]}"; do
    if [ ! -f "$f" ]; then
        touch "$f"
        echo "  created  → $f"
    else
        echo "  exists   → $f  (not overwritten)"
    fi
done

echo ""

# ── 3. Create .gitignore if not present ──────────────────
echo "[ 3 / 3 ]  Checking .gitignore..."

if [ ! -f ".gitignore" ]; then
cat > .gitignore << 'GITIGNORE'
# Data — download separately via Kaggle API
data/

# Results — generated by training scripts
results/

# Logs
logs/

# Python cache
__pycache__/
*.py[cod]
*.pyo
.ipynb_checkpoints/

# Conda / pip
*.egg-info/
dist/
build/
.env

# OS files
.DS_Store
Thumbs.db

# Credentials — never commit these
*.json
kaggle.json
GITIGNORE
    echo "  created  → .gitignore"
else
    echo "  exists   → .gitignore  (not overwritten)"
fi

echo ""
echo "============================================================"
echo "  Setup complete."
echo ""
echo "  Next steps:"
echo "    1. conda env create -f environment.yml"
echo "    2. conda activate OAIKaggle"
echo "    3. Download data (see README.md for instructions)"
echo "    4. Run: python src/train.py --help"
echo "============================================================"
echo ""
