version: "3.9"

services:
  train:
    build: ..
    runtime: nvidia
    volumes:
      - ../data:/app/data
      - ../checkpoints:/app/checkpoints
      - ../reports:/app/reports
    command: python scripts/train_model.py --config config/config.yaml --model resnet50
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  validate:
    build: ..
    volumes:
      - ../data:/app/data
      - ../checkpoints:/app/checkpoints
      - ../reports:/app/reports
    command: python scripts/external_validate.py --config config/config.yaml
